apiVersion: v1
kind: Service
metadata:
  name: appdeploy
spec:
  selector:
    app: flasknode
  ports:
  - protocol: TCP
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdeploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
        - name: flasknode
          image: imprateekpatel/python_helloapp:{{version}}
          ports:
            - containerPort: 5000

