---
- name: create a cloudformation stack
  amazon.aws.cloudformation:
    stack_name: {{cft_name}}
    state: "present"
    region: "us-east-1"
    disable_rollback: true
    template: "files/service.json"
    template_parameters:
      EcsClusterName: "python"
      Env: "envvalue"
      EcsContainerMemory: "m1.small"
      EcsContainerCpu: 2
    tags:
      Stack: "ansible-cloudformation"
