---
  tasks:
      - name: fetch the ip of the instance
        shell: hostname -i
        register: hostmachine

      - name: Temaplate Service
        template: src="deployment.yaml.j2" dest="deployment.yaml"
        delegate_to: localhost

      - name: apply kubernetes deployment
        shell: "kubectl apply -f deployment.yaml"
        register: result

      - name: Check Service Status
        uri:
          url: "{{hostmachine}}//:"
        register: output
        until: (output.json == "hello world")
        retries: 20
        delay: 30
